site_name: Gerencia pp
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate # modo oscuro
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search:
  - mkdocstrings:
      handlers:
        python:
          paths: [src]

nav:
  - Inicio: index.md
  - Referencia Tecnica: 
    - Referencias: referencia_tecnica/api.md
    - Comandos: referencia_tecnica/comandos.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences