site_name: Gestión de Supermercado - Código Limpio
site_description: Documentación técnica del backend y lógica de negocio con Arquitectura Limpia

theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate # modo oscuro
      primary: teal
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - code.copy

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [., src]

nav:
  - Inicio: index.md
  - Inicialización: inicializa_el_proyecto.md
  - Arquitectura del Sistema: arquitectura.md
  - Lógica de Negocio (Services):
    - Gestión de Usuarios: servicios/usuarios.md
    - Catálogo de Productos: servicios/productos.md
    - Carrito de Compras: servicios/carrito.md
  - Referencias API: api.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight
  - pymdownx.inlinehilite